// automatically generated by the FlatBuffers compiler, do not modify

package com.teamnova.server.object;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class AllUser extends Table {
  public static AllUser getRootAsAllUser(ByteBuffer _bb) { return getRootAsAllUser(_bb, new AllUser()); }
  public static AllUser getRootAsAllUser(ByteBuffer _bb, AllUser obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public AllUser __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public UserInfo AllList(int j) { return AllList(new UserInfo(), j); }
  public UserInfo AllList(UserInfo obj, int j) { int o = __offset(4); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int AllListLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }

  public static int createAllUser(FlatBufferBuilder builder,
      int AllListOffset) {
    builder.startObject(1);
    AllUser.addAllList(builder, AllListOffset);
    return AllUser.endAllUser(builder);
  }

  public static void startAllUser(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addAllList(FlatBufferBuilder builder, int AllListOffset) { builder.addOffset(0, AllListOffset, 0); }
  public static int createAllListVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startAllListVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endAllUser(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

