// automatically generated by the FlatBuffers compiler, do not modify

package com.teamnova.server.object;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class AttackInfo extends Table {
  public static AttackInfo getRootAsAttackInfo(ByteBuffer _bb) { return getRootAsAttackInfo(_bb, new AttackInfo()); }
  public static AttackInfo getRootAsAttackInfo(ByteBuffer _bb, AttackInfo obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public AttackInfo __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int AttackerID() { int o = __offset(4); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public int TargetID() { int o = __offset(6); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public int AttackType() { int o = __offset(8); return o != 0 ? bb.getInt(o + bb_pos) : 0; }

  public static int createAttackInfo(FlatBufferBuilder builder,
      int AttackerID,
      int TargetID,
      int AttackType) {
    builder.startObject(3);
    AttackInfo.addAttackType(builder, AttackType);
    AttackInfo.addTargetID(builder, TargetID);
    AttackInfo.addAttackerID(builder, AttackerID);
    return AttackInfo.endAttackInfo(builder);
  }

  public static void startAttackInfo(FlatBufferBuilder builder) { builder.startObject(3); }
  public static void addAttackerID(FlatBufferBuilder builder, int AttackerID) { builder.addInt(0, AttackerID, 0); }
  public static void addTargetID(FlatBufferBuilder builder, int TargetID) { builder.addInt(1, TargetID, 0); }
  public static void addAttackType(FlatBufferBuilder builder, int AttackType) { builder.addInt(2, AttackType, 0); }
  public static int endAttackInfo(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

