// automatically generated by the FlatBuffers compiler, do not modify

package com.teamnova.server.object;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class BuyRequest extends Table {
  public static BuyRequest getRootAsBuyRequest(ByteBuffer _bb) { return getRootAsBuyRequest(_bb, new BuyRequest()); }
  public static BuyRequest getRootAsBuyRequest(ByteBuffer _bb, BuyRequest obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public BuyRequest __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public boolean request() { int o = __offset(4); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }

  public static int createBuyRequest(FlatBufferBuilder builder,
      boolean request) {
    builder.startObject(1);
    BuyRequest.addRequest(builder, request);
    return BuyRequest.endBuyRequest(builder);
  }

  public static void startBuyRequest(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addRequest(FlatBufferBuilder builder, boolean request) { builder.addBoolean(0, request, false); }
  public static int endBuyRequest(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

