// automatically generated by the FlatBuffers compiler, do not modify

package com.teamnova.server.object;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class ChatMessage extends Table {
  public static ChatMessage getRootAsChatMessage(ByteBuffer _bb) { return getRootAsChatMessage(_bb, new ChatMessage()); }
  public static ChatMessage getRootAsChatMessage(ByteBuffer _bb, ChatMessage obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public ChatMessage __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String SenderID() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer SenderIDAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer SenderIDInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public String ChatMsg() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer ChatMsgAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer ChatMsgInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }
  public int GameState() { int o = __offset(8); return o != 0 ? bb.getInt(o + bb_pos) : 0; }

  public static int createChatMessage(FlatBufferBuilder builder,
      int SenderIDOffset,
      int ChatMsgOffset,
      int GameState) {
    builder.startObject(3);
    ChatMessage.addGameState(builder, GameState);
    ChatMessage.addChatMsg(builder, ChatMsgOffset);
    ChatMessage.addSenderID(builder, SenderIDOffset);
    return ChatMessage.endChatMessage(builder);
  }

  public static void startChatMessage(FlatBufferBuilder builder) { builder.startObject(3); }
  public static void addSenderID(FlatBufferBuilder builder, int SenderIDOffset) { builder.addOffset(0, SenderIDOffset, 0); }
  public static void addChatMsg(FlatBufferBuilder builder, int ChatMsgOffset) { builder.addOffset(1, ChatMsgOffset, 0); }
  public static void addGameState(FlatBufferBuilder builder, int GameState) { builder.addInt(2, GameState, 0); }
  public static int endChatMessage(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

