// automatically generated by the FlatBuffers compiler, do not modify

package com.teamnova.server.object;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class GameState extends Table {
  public static GameState getRootAsGameState(ByteBuffer _bb) { return getRootAsGameState(_bb, new GameState()); }
  public static GameState getRootAsGameState(ByteBuffer _bb, GameState obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public GameState __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Code() { int o = __offset(4); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public int UserIDCode() { int o = __offset(6); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public int MaxPoint() { int o = __offset(8); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public String UserID() { int o = __offset(10); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer UserIDAsByteBuffer() { return __vector_as_bytebuffer(10, 1); }
  public ByteBuffer UserIDInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 10, 1); }

  public static int createGameState(FlatBufferBuilder builder,
      int Code,
      int UserIDCode,
      int MaxPoint,
      int UserIDOffset) {
    builder.startObject(4);
    GameState.addUserID(builder, UserIDOffset);
    GameState.addMaxPoint(builder, MaxPoint);
    GameState.addUserIDCode(builder, UserIDCode);
    GameState.addCode(builder, Code);
    return GameState.endGameState(builder);
  }

  public static void startGameState(FlatBufferBuilder builder) { builder.startObject(4); }
  public static void addCode(FlatBufferBuilder builder, int Code) { builder.addInt(0, Code, 0); }
  public static void addUserIDCode(FlatBufferBuilder builder, int UserIDCode) { builder.addInt(1, UserIDCode, 0); }
  public static void addMaxPoint(FlatBufferBuilder builder, int MaxPoint) { builder.addInt(2, MaxPoint, 0); }
  public static void addUserID(FlatBufferBuilder builder, int UserIDOffset) { builder.addOffset(3, UserIDOffset, 0); }
  public static int endGameState(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

