// automatically generated by the FlatBuffers compiler, do not modify

package com.teamnova.server.object;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class GameEnd extends Table {
  public static GameEnd getRootAsGameEnd(ByteBuffer _bb) { return getRootAsGameEnd(_bb, new GameEnd()); }
  public static GameEnd getRootAsGameEnd(ByteBuffer _bb, GameEnd obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public GameEnd __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public boolean IsEnd() { int o = __offset(4); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }

  public static int createGameEnd(FlatBufferBuilder builder,
      boolean IsEnd) {
    builder.startObject(1);
    GameEnd.addIsEnd(builder, IsEnd);
    return GameEnd.endGameEnd(builder);
  }

  public static void startGameEnd(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addIsEnd(FlatBufferBuilder builder, boolean IsEnd) { builder.addBoolean(0, IsEnd, false); }
  public static int endGameEnd(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

