// automatically generated by the FlatBuffers compiler, do not modify

package com.teamnova.server.object;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class GameStartInfo extends Table {
  public static GameStartInfo getRootAsGameStartInfo(ByteBuffer _bb) { return getRootAsGameStartInfo(_bb, new GameStartInfo()); }
  public static GameStartInfo getRootAsGameStartInfo(ByteBuffer _bb, GameStartInfo obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public GameStartInfo __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int StartGameRoomnumber() { int o = __offset(4); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public boolean isstart() { int o = __offset(6); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }
  public boolean isloadingcomplete() { int o = __offset(8); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }
  public int count() { int o = __offset(10); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public boolean iscounting() { int o = __offset(12); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }

  public static int createGameStartInfo(FlatBufferBuilder builder,
      int StartGameRoomnumber,
      boolean isstart,
      boolean isloadingcomplete,
      int count,
      boolean iscounting) {
    builder.startObject(5);
    GameStartInfo.addCount(builder, count);
    GameStartInfo.addStartGameRoomnumber(builder, StartGameRoomnumber);
    GameStartInfo.addIscounting(builder, iscounting);
    GameStartInfo.addIsloadingcomplete(builder, isloadingcomplete);
    GameStartInfo.addIsstart(builder, isstart);
    return GameStartInfo.endGameStartInfo(builder);
  }

  public static void startGameStartInfo(FlatBufferBuilder builder) { builder.startObject(5); }
  public static void addStartGameRoomnumber(FlatBufferBuilder builder, int StartGameRoomnumber) { builder.addInt(0, StartGameRoomnumber, 0); }
  public static void addIsstart(FlatBufferBuilder builder, boolean isstart) { builder.addBoolean(1, isstart, false); }
  public static void addIsloadingcomplete(FlatBufferBuilder builder, boolean isloadingcomplete) { builder.addBoolean(2, isloadingcomplete, false); }
  public static void addCount(FlatBufferBuilder builder, int count) { builder.addInt(3, count, 0); }
  public static void addIscounting(FlatBufferBuilder builder, boolean iscounting) { builder.addBoolean(4, iscounting, false); }
  public static int endGameStartInfo(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

