// automatically generated by the FlatBuffers compiler, do not modify

package com.teamnova.server.object;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class ItemBuy extends Table {
  public static ItemBuy getRootAsItemBuy(ByteBuffer _bb) { return getRootAsItemBuy(_bb, new ItemBuy()); }
  public static ItemBuy getRootAsItemBuy(ByteBuffer _bb, ItemBuy obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public ItemBuy __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Potion100() { int o = __offset(4); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public int Potion50() { int o = __offset(6); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public int TotalPrice() { int o = __offset(8); return o != 0 ? bb.getInt(o + bb_pos) : 0; }

  public static int createItemBuy(FlatBufferBuilder builder,
      int Potion_100,
      int Potion_50,
      int TotalPrice) {
    builder.startObject(3);
    ItemBuy.addTotalPrice(builder, TotalPrice);
    ItemBuy.addPotion50(builder, Potion_50);
    ItemBuy.addPotion100(builder, Potion_100);
    return ItemBuy.endItemBuy(builder);
  }

  public static void startItemBuy(FlatBufferBuilder builder) { builder.startObject(3); }
  public static void addPotion100(FlatBufferBuilder builder, int Potion100) { builder.addInt(0, Potion100, 0); }
  public static void addPotion50(FlatBufferBuilder builder, int Potion50) { builder.addInt(1, Potion50, 0); }
  public static void addTotalPrice(FlatBufferBuilder builder, int TotalPrice) { builder.addInt(2, TotalPrice, 0); }
  public static int endItemBuy(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

