// automatically generated by the FlatBuffers compiler, do not modify

package com.teamnova.server.object;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class ItemUsing extends Table {
  public static ItemUsing getRootAsItemUsing(ByteBuffer _bb) { return getRootAsItemUsing(_bb, new ItemUsing()); }
  public static ItemUsing getRootAsItemUsing(ByteBuffer _bb, ItemUsing obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public ItemUsing __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Type() { int o = __offset(4); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public int UserID() { int o = __offset(6); return o != 0 ? bb.getInt(o + bb_pos) : 0; }

  public static int createItemUsing(FlatBufferBuilder builder,
      int Type,
      int UserID) {
    builder.startObject(2);
    ItemUsing.addUserID(builder, UserID);
    ItemUsing.addType(builder, Type);
    return ItemUsing.endItemUsing(builder);
  }

  public static void startItemUsing(FlatBufferBuilder builder) { builder.startObject(2); }
  public static void addType(FlatBufferBuilder builder, int Type) { builder.addInt(0, Type, 0); }
  public static void addUserID(FlatBufferBuilder builder, int UserID) { builder.addInt(1, UserID, 0); }
  public static int endItemUsing(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

