// automatically generated by the FlatBuffers compiler, do not modify

package com.teamnova.server.object;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class LoginData extends Table {
  public static LoginData getRootAsLoginData(ByteBuffer _bb) { return getRootAsLoginData(_bb, new LoginData()); }
  public static LoginData getRootAsLoginData(ByteBuffer _bb, LoginData obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public LoginData __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String ID() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer IDAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer IDInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public String Password() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer PasswordAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer PasswordInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }
  public boolean IsLoginOk() { int o = __offset(8); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }
  public int IDCode() { int o = __offset(10); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public int Potion100() { int o = __offset(12); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public int Potion50() { int o = __offset(14); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public int Gold() { int o = __offset(16); return o != 0 ? bb.getInt(o + bb_pos) : 0; }

  public static int createLoginData(FlatBufferBuilder builder,
      int IDOffset,
      int PasswordOffset,
      boolean IsLoginOk,
      int IDCode,
      int Potion100,
      int Potion50,
      int Gold) {
    builder.startObject(7);
    LoginData.addGold(builder, Gold);
    LoginData.addPotion50(builder, Potion50);
    LoginData.addPotion100(builder, Potion100);
    LoginData.addIDCode(builder, IDCode);
    LoginData.addPassword(builder, PasswordOffset);
    LoginData.addID(builder, IDOffset);
    LoginData.addIsLoginOk(builder, IsLoginOk);
    return LoginData.endLoginData(builder);
  }

  public static void startLoginData(FlatBufferBuilder builder) { builder.startObject(7); }
  public static void addID(FlatBufferBuilder builder, int IDOffset) { builder.addOffset(0, IDOffset, 0); }
  public static void addPassword(FlatBufferBuilder builder, int PasswordOffset) { builder.addOffset(1, PasswordOffset, 0); }
  public static void addIsLoginOk(FlatBufferBuilder builder, boolean IsLoginOk) { builder.addBoolean(2, IsLoginOk, false); }
  public static void addIDCode(FlatBufferBuilder builder, int IDCode) { builder.addInt(3, IDCode, 0); }
  public static void addPotion100(FlatBufferBuilder builder, int Potion100) { builder.addInt(4, Potion100, 0); }
  public static void addPotion50(FlatBufferBuilder builder, int Potion50) { builder.addInt(5, Potion50, 0); }
  public static void addGold(FlatBufferBuilder builder, int Gold) { builder.addInt(6, Gold, 0); }
  public static int endLoginData(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

