// automatically generated by the FlatBuffers compiler, do not modify

package com.teamnova.server.object;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class MonsterData extends Table {
  public static MonsterData getRootAsMonsterData(ByteBuffer _bb) { return getRootAsMonsterData(_bb, new MonsterData()); }
  public static MonsterData getRootAsMonsterData(ByteBuffer _bb, MonsterData obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public MonsterData __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int playerName() { int o = __offset(4); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public int health() { int o = __offset(6); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public Location monsterLocation() { return monsterLocation(new Location()); }
  public Location monsterLocation(Location obj) { int o = __offset(8); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }
  public boolean IsAlive() { int o = __offset(10); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }
  public boolean IsAttacking() { int o = __offset(12); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }
  public int AttackCountNumber() { int o = __offset(14); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public int MonsterType() { int o = __offset(16); return o != 0 ? bb.getInt(o + bb_pos) : 0; }

  public static int createMonsterData(FlatBufferBuilder builder,
      int player_name,
      int health,
      int monsterLocationOffset,
      boolean IsAlive,
      boolean IsAttacking,
      int AttackCountNumber,
      int MonsterType) {
    builder.startObject(7);
    MonsterData.addMonsterType(builder, MonsterType);
    MonsterData.addAttackCountNumber(builder, AttackCountNumber);
    MonsterData.addMonsterLocation(builder, monsterLocationOffset);
    MonsterData.addHealth(builder, health);
    MonsterData.addPlayerName(builder, player_name);
    MonsterData.addIsAttacking(builder, IsAttacking);
    MonsterData.addIsAlive(builder, IsAlive);
    return MonsterData.endMonsterData(builder);
  }

  public static void startMonsterData(FlatBufferBuilder builder) { builder.startObject(7); }
  public static void addPlayerName(FlatBufferBuilder builder, int playerName) { builder.addInt(0, playerName, 0); }
  public static void addHealth(FlatBufferBuilder builder, int health) { builder.addInt(1, health, 0); }
  public static void addMonsterLocation(FlatBufferBuilder builder, int monsterLocationOffset) { builder.addOffset(2, monsterLocationOffset, 0); }
  public static void addIsAlive(FlatBufferBuilder builder, boolean IsAlive) { builder.addBoolean(3, IsAlive, false); }
  public static void addIsAttacking(FlatBufferBuilder builder, boolean IsAttacking) { builder.addBoolean(4, IsAttacking, false); }
  public static void addAttackCountNumber(FlatBufferBuilder builder, int AttackCountNumber) { builder.addInt(5, AttackCountNumber, 0); }
  public static void addMonsterType(FlatBufferBuilder builder, int MonsterType) { builder.addInt(6, MonsterType, 0); }
  public static int endMonsterData(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

