// automatically generated by the FlatBuffers compiler, do not modify

package com.teamnova.server.object;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class MoveMonster extends Table {
  public static MoveMonster getRootAsMoveMonster(ByteBuffer _bb) { return getRootAsMoveMonster(_bb, new MoveMonster()); }
  public static MoveMonster getRootAsMoveMonster(ByteBuffer _bb, MoveMonster obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public MoveMonster __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int WhichMonster() { int o = __offset(4); return o != 0 ? bb.getInt(o + bb_pos) : 0; }

  public static int createMoveMonster(FlatBufferBuilder builder,
      int WhichMonster) {
    builder.startObject(1);
    MoveMonster.addWhichMonster(builder, WhichMonster);
    return MoveMonster.endMoveMonster(builder);
  }

  public static void startMoveMonster(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addWhichMonster(FlatBufferBuilder builder, int WhichMonster) { builder.addInt(0, WhichMonster, 0); }
  public static int endMoveMonster(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

