// automatically generated by the FlatBuffers compiler, do not modify

package com.teamnova.server.object;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class MoveOK extends Table {
  public static MoveOK getRootAsMoveOK(ByteBuffer _bb) { return getRootAsMoveOK(_bb, new MoveOK()); }
  public static MoveOK getRootAsMoveOK(ByteBuffer _bb, MoveOK obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public MoveOK __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public boolean flag() { int o = __offset(4); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }

  public static int createMoveOK(FlatBufferBuilder builder,
      boolean flag) {
    builder.startObject(1);
    MoveOK.addFlag(builder, flag);
    return MoveOK.endMoveOK(builder);
  }

  public static void startMoveOK(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addFlag(FlatBufferBuilder builder, boolean flag) { builder.addBoolean(0, flag, false); }
  public static int endMoveOK(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

