// automatically generated by the FlatBuffers compiler, do not modify

package com.teamnova.server.object;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class RankUser extends Table {
  public static RankUser getRootAsRankUser(ByteBuffer _bb) { return getRootAsRankUser(_bb, new RankUser()); }
  public static RankUser getRootAsRankUser(ByteBuffer _bb, RankUser obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public RankUser __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String userid() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer useridAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer useridInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public int point() { int o = __offset(6); return o != 0 ? bb.getInt(o + bb_pos) : 0; }

  public static int createRankUser(FlatBufferBuilder builder,
      int useridOffset,
      int point) {
    builder.startObject(2);
    RankUser.addPoint(builder, point);
    RankUser.addUserid(builder, useridOffset);
    return RankUser.endRankUser(builder);
  }

  public static void startRankUser(FlatBufferBuilder builder) { builder.startObject(2); }
  public static void addUserid(FlatBufferBuilder builder, int useridOffset) { builder.addOffset(0, useridOffset, 0); }
  public static void addPoint(FlatBufferBuilder builder, int point) { builder.addInt(1, point, 0); }
  public static int endRankUser(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

