// automatically generated by the FlatBuffers compiler, do not modify

package com.teamnova.server.object;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class Revival extends Table {
  public static Revival getRootAsRevival(ByteBuffer _bb) { return getRootAsRevival(_bb, new Revival()); }
  public static Revival getRootAsRevival(ByteBuffer _bb, Revival obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public Revival __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public boolean IsPerfect() { int o = __offset(4); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }

  public static int createRevival(FlatBufferBuilder builder,
      boolean IsPerfect) {
    builder.startObject(1);
    Revival.addIsPerfect(builder, IsPerfect);
    return Revival.endRevival(builder);
  }

  public static void startRevival(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addIsPerfect(FlatBufferBuilder builder, boolean IsPerfect) { builder.addBoolean(0, IsPerfect, false); }
  public static int endRevival(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

