// automatically generated by the FlatBuffers compiler, do not modify

package com.teamnova.server.object;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class SystemTime extends Table {
  public static SystemTime getRootAsSystemTime(ByteBuffer _bb) { return getRootAsSystemTime(_bb, new SystemTime()); }
  public static SystemTime getRootAsSystemTime(ByteBuffer _bb, SystemTime obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public SystemTime __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Time() { int o = __offset(4); return o != 0 ? bb.getInt(o + bb_pos) : 0; }

  public static int createSystemTime(FlatBufferBuilder builder,
      int Time) {
    builder.startObject(1);
    SystemTime.addTime(builder, Time);
    return SystemTime.endSystemTime(builder);
  }

  public static void startSystemTime(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addTime(FlatBufferBuilder builder, int Time) { builder.addInt(0, Time, 0); }
  public static int endSystemTime(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

