// automatically generated by the FlatBuffers compiler, do not modify

package com.teamnova.server.object;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class SystemMessage extends Table {
  public static SystemMessage getRootAsSystemMessage(ByteBuffer _bb) { return getRootAsSystemMessage(_bb, new SystemMessage()); }
  public static SystemMessage getRootAsSystemMessage(ByteBuffer _bb, SystemMessage obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public SystemMessage __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String message() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer messageAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer messageInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public int type() { int o = __offset(6); return o != 0 ? bb.getInt(o + bb_pos) : 0; }

  public static int createSystemMessage(FlatBufferBuilder builder,
      int messageOffset,
      int type) {
    builder.startObject(2);
    SystemMessage.addType(builder, type);
    SystemMessage.addMessage(builder, messageOffset);
    return SystemMessage.endSystemMessage(builder);
  }

  public static void startSystemMessage(FlatBufferBuilder builder) { builder.startObject(2); }
  public static void addMessage(FlatBufferBuilder builder, int messageOffset) { builder.addOffset(0, messageOffset, 0); }
  public static void addType(FlatBufferBuilder builder, int type) { builder.addInt(1, type, 0); }
  public static int endSystemMessage(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

