// automatically generated by the FlatBuffers compiler, do not modify

package com.teamnova.server.object;

public final class Type {
  private Type() { }
  public static final byte NONE = 0;
  public static final byte LoginData = 1;
  public static final byte SignUpData = 2;
  public static final byte GameState = 3;
  public static final byte AllUser = 4;
  public static final byte RoomInfo = 5;
  public static final byte RoomList = 6;
  public static final byte GameReadyInfo = 7;
  public static final byte LeaveRoom = 8;
  public static final byte GameStartInfo = 9;
  public static final byte CheckPassword = 10;
  public static final byte ChatMessage = 11;
  public static final byte AttackInfo = 12;
  public static final byte PlayerData = 13;
  public static final byte GameResult = 14;
  public static final byte TopRanking = 15;
  public static final byte MonsterData = 16;
  public static final byte SystemMessage = 17;
  public static final byte SystemTime = 18;
  public static final byte SpawnOK = 19;
  public static final byte MoveMonster = 20;
  public static final byte MoveOK = 21;
  public static final byte SpawnMonsterData = 22;
  public static final byte MyData = 23;
  public static final byte Revival = 24;
  public static final byte GameEnd = 25;
  public static final byte ItemUsing = 26;
  public static final byte RefreshItem = 27;
  public static final byte ItemBuy = 28;
  public static final byte BuyRequest = 29;

  public static final String[] names = { "NONE", "LoginData", "SignUpData", "GameState", "AllUser", "RoomInfo", "RoomList", "GameReadyInfo", "LeaveRoom", "GameStartInfo", "CheckPassword", "ChatMessage", "AttackInfo", "PlayerData", "GameResult", "TopRanking", "MonsterData", "SystemMessage", "SystemTime", "SpawnOK", "MoveMonster", "MoveOK", "SpawnMonsterData", "MyData", "Revival", "GameEnd", "ItemUsing", "RefreshItem", "ItemBuy", "BuyRequest", };

  public static String name(int e) { return names[e]; }
}

